### ISSUE TITLE
Long pressing of a key causes sounds to play for longer than necessary

### ISSUE THREAD

**Issue by makhlwf** [ahmedthebest31/navsounds#11]
When long click on a button The sounds likely added to a queue so if I pressed on button for like 30 seconds I will hear sounds for like 2 minutes 
I hope you understand this and I hope you can fix it

**Comment by ahmedthebest31** [comment]
I tried a lot to make this Issue as you explained on my machine, 
but it did not happen to me
Can you give me a recording of the problem to help me understand and solve it?

and witch version of Nvda you use and witch version of navsound
